
version: '3.7'

services:
  db1:
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=db1
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
  db2:
    image: postgres:13.1-alpine
    ports:
      - 6432:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=db2
    volumes:
      - ./docker-entrypoint-initdb2.d:/docker-entrypoint-initdb.d:ro
  db3:
    image: postgres:13.1-alpine
    ports:
      - 7432:5432
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=app
      - POSTGRES_DB=db3
    volumes:
      - ./docker-entrypoint-initdb3.d:/docker-entrypoint-initdb.d:ro
